version: "3.9"
services:
  dev-db:
    build: .
    image: postgres:13
    ports:
      - "5434:5434" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - FoxTails
networks:
  FoxTails:
